### ISSUE TITLE
There's no code yet

### ISSUE THREAD

**Issue by kbshimmyo** [ramanshah/bread#1]
It's been 25 minutes since the initial commit and there's no code yet.  :)

**Comment by ramanshah** [comment]
- [x] Figure out the right `stack` template
- [x] Fashion a reasonable `.gitignore`
- [x] Verify installability
- [x] Let there be code!

**Comment by kbshimmyo** [comment]
:bread:
:baguette_bread:

**Comment by ramanshah** [comment]
In the interest of KISS and perfect-is-the-enemy-of-done, I think I'll use the `simple` template. I'll leave partitioning between library, executable, and test sections for a future project with more that could go wrong.

**Comment by ramanshah** [comment]
There's code. But I'll put off closing this until I can verify installability of the codebase's library in a separate project.

**Comment by ramanshah** [comment]
Moving the goalposts to verifying that someone call install and run `bread` on their computer (say a Mac) from a cold start.

**Comment by ramanshah** [comment]
Success! I got Joerg and Marcus from the Haskell meetup squared away via stack.
